### ISSUE TITLE
Return better error when invalid key present in config

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#37]
If you accidentally write something like this:

```yaml
actions:
  deploy:
    comand: ./deploy-foo.sh
    description: Deploy foo
```

In which the `command` key is misspelled `comand`, such as due to a typographical error, `ops` returns:

``` 
 Running '' from ops.yml in environment 'ci'...
 /usr/local/bundle/gems/ops_team-0.9.7/lib/action.rb:16:in `exec': No such file or directory -  (Errno::ENOENT)
 	from /usr/local/bundle/gems/ops_team-0.9.7/lib/action.rb:16:in `run'
 	from /usr/local/bundle/gems/ops_team-0.9.7/lib/ops.rb:62:in `run_action'
 	from /usr/local/bundle/gems/ops_team-0.9.7/lib/ops.rb:38:in `run'
 	from /usr/local/bundle/gems/ops_team-0.9.7/bin/ops:8:in `<top (required)>'
 	from /usr/local/bundle/bin/ops:23:in `load'
 	from /usr/local/bundle/bin/ops:23:in `<main>'
(exits with retval 1)
```

`ops` should provide a better syntax error and possibly have a "Did you mean: command?`" for cases like this (similar to #34)

**Comment by nickthecook** [comment]
👍

**Comment by nickthecook** [comment]
In 0.14.3 it prints:

`Error(s) running action 'deploy' No 'command' specified in 'action'.`
