### ISSUE TITLE
Handle empty/unreadable config file

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#69]
By default, `ops` attempts to load environment variables from `config/$environment/config.json` and `config/$environment/secrets.(e)json`. But if these are empty or malformed, `ops` gives the cryptic error:

```console
Traceback (most recent call last):
        7: from /Users/cronos/.gem/ruby/2.7.5/bin/ops:23:in `<main>'
        6: from /Users/cronos/.gem/ruby/2.7.5/bin/ops:23:in `load'
        5: from /Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/bin/ops:30:in `<top (required)>'
        4: from /Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/lib/ops.rb:46:in `run'
        3: from /Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/lib/runner.rb:31:in `run'
        2: from /Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/lib/runner.rb:50:in `do_before_all'
        1: from /Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/lib/app_config.rb:8:in `load'
/Users/cronos/.gem/ruby/2.7.5/gems/ops_team-1.14.1/lib/app_config.rb:35:in `load': undefined method `[]' for nil:NilClass (NoMethodError)
```

A common reason for these files existing but being empty is the developer preemptively creating them without populating them. Putting a simple empty JSON object `{}` in them fixes the issue, but it would be nice if `ops` ignored the file if the developer forgot to do even that. Or if it gave some error message about the file existing but not having anything it can read/load.

**Comment by nickthecook** [comment]
1.16.2.rc1 has a fix for this. LMK if that works for you!
